### ISSUE TITLE
Trying to create configuration tool for Perixx MX-3100 Mouse

### ISSUE THREAD

**Issue by successtheman** [lolo101/px1800kbd#4]
@lolo101 I saw you have a driver for the PX1800 here and was wondering if maybe you would like to help me develop a configuration tool for the Perixx MX-3100 mouse. I figured since you already made a driver for one Perixx device you might have some tricks that would help me out.

**Comment by lolo101** [comment]
Hi @rjmxtechnology and thanks for your interest in this project !
I don't have much experience in driver development. This project is forked from another keybd driver that I just adapted to the PX1800. There were no specifics for the PX1800 besides its layout.
I would be happy to help but I have no idea how to configure the MX3100... When you have a project set up, I would be happy to help though.

**Comment by successtheman** [comment]
I'm mainly trying to make a configuration tool for it for Linux. So not so much a driver

**Comment by lolo101** [comment]
Yes I got that :) Do you know of some API to use to configure the mouse ? I wonder if that would not be related to its driver somehow...

**Comment by davidebeatrici** [comment]
https://github.com/pzl/mx3100drv

**Comment by successtheman** [comment]
Thanks for referring me to this, but I was the one who contacted him about this and asked him to help me make it. So I already saw this and had somewhat solved the issue :)

On July 16, 2017 1:40:39 PM CDT, Davide Beatrici <notifications@github.com> wrote:
>https://github.com/pzl/mx3100drv
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/lolo101/px1800kbd/issues/4#issuecomment-315628299

-- 
Thank You,

    rjmxtechnology
