### ISSUE TITLE
Not working after reboot on kernel 4.15

### ISSUE THREAD

**Issue by eathtespagheti** [lolo101/px1800kbd#5]
With 4.10 everything was working fine, but from when I've upgraded to 4.15 every time I reboot my computer i need to reinstall the driver to make it work

**Comment by lolo101** [comment]
Hi @Fabi0Z and thank you for your feedback.
Unfortunately I could test up to 4.9 only (and didn't notice any issue).
Could you inspect the `dmesg` log for any driver related message ?

**Comment by lolo101** [comment]
Ok I moved to 4.15 and have issues with the driver too.
Let's investigate

**Comment by eathtespagheti** [comment]
Hi @lolo101 , I've done some tests and I've noticed that if you Install the driver without dkms and THEN upgrade/downgrade to another kernel version everything works, but if you installl the driver with dkms and then install any kernel version, that kernel doesn't recognize the keyboard at all, and there's no way to make it work, not even resinstalling and purging that kernel version

**Comment by lolo101** [comment]
Hmm
What I see on my machine is, despite the "quirk" file in `/etc/modprobe.d/usbhid.conf` to prevent usbhid to claim the keyboard, the keyboard is claim by usbhid anyway.
If I run `rmmod usbhid && modprobe usbhid quirks=0x0c45:0x7603:0x00000004` the keyboard is correctly ignored by usbhid though.

**Comment by lolo101** [comment]
To me it looks like static param defined in `/etc/modprob.d/...` is not taken into account (though if the parameter is incorrectly formatted you get a warning in the kernel messages) but the dynamic parameter given by command line is taken into account.

**Comment by eathtespagheti** [comment]
I've tried upgrading to 4.15.9 and also with this the keyboard doesn't work at all, so I'm unable to run `rmmod usbhid && modprobe usbhid quirks=0x0c45:0x7603:0x00000004`

There's a way to completely remove the driver? So I can try to run the new version without it and see whats happen if I reinstall it using the new kernel

**Comment by lolo101** [comment]
> the keyboard doesn't work at all

You mean you cannot event type a letter ? That have to mean no driver has claimed the keyboard.
If px1800kbd is installed, you can unplug/replug the keyboard so it will claim it.

`rmmod` should remove the driver. `dkms remove` should completely uninstall it. That's how I remove it before building & testing a new version :)

The more I search, the more I'm convinced there is an issue with config-file based quirks option.
I found another reference to the same issue : https://askubuntu.com/questions/605251/dkms-installed-kernel-module-but-not-working-after-reboot/606359

I'm currently reading through usbhid sources and documenting on modprob to understand how the config file is loaded...

**Comment by lolo101** [comment]
@Fabi0Z as a workaround, you can still add the `usbhid.quirks=...` option to the kernel command line in your bootloader config (don't forget to update your bootloader afterwards)

**Comment by lolo101** [comment]
Ok, it looks like usbhid is not configured by modprobe on startup.

If I corrupt `/etc/modprobe.d/usbhid.conf` with an invalid quirk (for instance `0xzz`. However note that `0x000000z4` seems valid... But I think it's parsed as 0)
I dont see any error message with `dmesg`.
BUT if I run `rmmod usbhid && modprobe usbhid` it reads :
```
Could not parse HID quirk module param 0x0c45:0x7603:0xzz
```

**Comment by lolo101** [comment]
I got it : run `lsinitcpio /boot/initramfs-linux.img | grep usbhid`
If that line shows up :
```
usr/lib/modules/4.15.7-1-ARCH/kernel/usbhid.ko
```
That means the module is loaded from initramfs and requires initramfs to be configured.
I'm experimenting with various ways to achieve that.

See : https://wiki.archlinux.org/index.php/Kernel_modules

**Comment by lolo101** [comment]
*FIXED !*
That was very easy actually : since there already is a build hook for mkinitcpio named `modconf` that does exactly what we need (copy the modprobe conf into the initramfs), all I had to do is run `sudo mkinitcpio -p linux` and restart the system !

However I'm not sure that solution is convenient for all Linux distributions. I suppose it's safe enough if **mkinitcpio** is installed, but I need to experiment on some other distributions before update **install.sh**

**Comment by lolo101** [comment]
Actually it's a little risky to simply rebuild the initramfs, because you don't know what will get inside.

For instance when I rebuilt the initramfs, my WiFi USB dongle driver went inside and now I have errors during the boot sequence because the driver is loaded too soon...

**Comment by lolo101** [comment]
I'm quite reluctant to automatise the initramfs modification.
I added the procedure to the README and I think that's good enough to close that issue.

Please don't hesitate to reopen if needed.
