### ISSUE TITLE
success with Periboard 506 II keyboard

### ISSUE THREAD

**Issue by dcmorse** [lolo101/px1800kbd#6]
I couldn't find anywhere on the internet that said that this worked with Periboard 506 II keyboard, and I think it's important that the internet know that. I tested against Ubuntu 16.04 and the install instructions worked like a charm. A github issue seemed like a semi-reasonable place to record that information. Totally okay to close this non-issue issue.

**Comment by lolo101** [comment]
Thank you for your help !
I added a word about that in the README.
