### ISSUE TITLE
Compiling error: too many arguments to function

### ISSUE THREAD

**Issue by Damni81** [lolo101/px1800kbd#7]
Distribution: Arch Linux
Kernel: 5.19.1-arch2-1

After system update the driver doesn't compile any more.
Let me know if you need more info (first time I fill an issue on github).

```
make -C /lib/modules/5.19.1-arch2-1/build M=/mnt/box/downloads/px1800kbd modules
make[1]: Entering directory '/usr/lib/modules/5.19.1-arch2-1/build'
  CC [M]  /mnt/box/downloads/px1800kbd/px1800kbd.o
/mnt/box/downloads/px1800kbd/px1800kbd.c: In function ‘init_kbd_irq’:
/mnt/box/downloads/px1800kbd/px1800kbd.c:335:20: error: too many arguments to function ‘usb_maxpacket’
  335 |         int maxp = usb_maxpacket(dev, pipe, usb_pipeout(pipe));
      |                    ^~~~~~~~~~~~~
In file included from ./include/linux/usb/input.h:13,
                 from /mnt/box/downloads/px1800kbd/px1800kbd.c:28:
./include/linux/usb.h:1972:19: note: declared here
 1972 | static inline u16 usb_maxpacket(struct usb_device *udev, int pipe)
      |                   ^~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:249: /mnt/box/downloads/px1800kbd/px1800kbd.o] Error 1
make[1]: *** [Makefile:1843: /mnt/box/downloads/px1800kbd] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.19.1-arch2-1/build'
make: *** [Makefile:33: default] Error 2
```

**Comment by Dany-Dan** [comment]
Same problem here with same kernel on Arch Linux.
My solution to fix it (it works for me at least) :

- download the sources --> `git clone https://github.com/lolo101/px1800kbd.git`
- edit px1800kbd/px1800kbd.c file
- search for usb_maxpacket on line 335 --> `int maxp = usb_maxpacket(dev, pipe, usb_pipeout(pipe));`
- remove third argument --> `int maxp = usb_maxpacket(dev, pipe);`
- save and build the module

**Comment by Damni81** [comment]
OK, I have no idea what "usb_pipeout(pipe)" does, but your solution works.
Thanks!

**Comment by lolo101** [comment]
Hi @Damni81 and thank you very much for the report, and thanks to @Dany-Dan for the workaround :)
I am with the same kernel:
```
$ uname --kernel-release 
5.19.1-arch2-1
```
but didn't notice the issue...
I'll look at the functions `usb_maxpacket` and `usb_pipeout` and let you know

**Comment by lolo101** [comment]
Found this thread : https://lore.kernel.org/all/20220316161935.2049-9-mailhol.vincent@wanadoo.fr/

**Comment by lolo101** [comment]
Ok, I could reproduce the issue. Fixing the code...

**Comment by lolo101** [comment]
v3.0.0 is released and fixes this issue
